"use client";
import { motion } from "framer-motion";
import { ArrowRight, Download, Github, Linkedin, Mail, Sparkles } from "lucide-react";
import { CONTACT } from "@/data/site";

const nodes = ["User request", "AI agent", "Tools / APIs", "Automation", "Business result"];
export default function Hero() {
  return <section id="home" className="hero"><div className="hero-glow" /><div className="container hero-grid"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}><div className="status"><span /> Available for AI &amp; automation projects</div><h1>Hi, I&apos;m Yogita Jha.<strong>I build intelligent systems that automate real businesses.</strong></h1><p className="hero-copy">AI Automation Developer &amp; Full-Stack Engineer building AI agents, voice assistants, ERP systems and RAG applications with Python, FastAPI, React and modern LLMs.</p><div className="hero-actions"><a className="button" href="#projects">View my work <ArrowRight size={17} /></a><a className="button secondary" href="#contact">Let&apos;s work together</a><a className="text-button" href={CONTACT.resume} download><Download size={16} /> Resume</a></div><div className="socials"><a href={CONTACT.github} target="_blank" aria-label="GitHub"><Github /></a><a href={CONTACT.linkedin} target="_blank" aria-label="LinkedIn"><Linkedin /></a><a href={`mailto:${CONTACT.email}`} aria-label="Email"><Mail /></a></div></motion.div><motion.div className="workflow-card" initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .25, duration: .7 }}><div className="window-bar"><i /><i /><i /><span>agent.workflow</span></div><div className="workflow-title"><Sparkles size={17} /> Autonomous workflow</div><div className="workflow">{nodes.map((node, i) => <div key={node} className="workflow-row"><motion.div className={`workflow-node n${i}`} animate={{ boxShadow: ["0 0 0 rgba(84,230,165,0)", "0 0 24px rgba(84,230,165,.14)", "0 0 0 rgba(84,230,165,0)"] }} transition={{ duration: 3, delay: i * .35, repeat: Infinity }}>{String(i + 1).padStart(2, "0")}<span>{node}</span>{i === 1 && <b>thinking</b>}</motion.div>{i < nodes.length - 1 && <div className="connector"><i /></div>}</div>)}</div><div className="system-ok"><span /> System operational <code>98ms</code></div></motion.div></div></section>;
}
